### PR TITLE
Add settingsKey to Text

### PR DESCRIPTION
**Pull request by Beat-YT**

### CODE REVIEW

**Comment by SergioMorchon** [comment]
Hi @Beat-YT, do you have any link to some documentation example or something like that?
Because I think that property doesn't exist in [`Text`](https://dev.fitbit.com/build/reference/settings-api/#text). It's only for editable components, such as [`TextInput`](https://dev.fitbit.com/build/reference/settings-api/#textinput).

**Comment by Beat-YT** [comment]
Using settingsKey is my workaround to modify the text via the Companion

**Comment by SergioMorchon** [comment]
Do you knowif that is a supported and documented use case @Hexxeh?

**Comment by Beat-YT** [comment]
It's not documented but it's working fine

**Comment by Hexxeh** [comment]
I think so yes. @orviwan something to add to docs too?

**Comment by Beat-YT** [comment]
So?

**Comment by Beat-YT** [comment]
What's the conclusion?

**Comment by SergioMorchon** [comment]
> So?

> What's the conclusion?

I'll merge your changes, thanks for your contribution!

**Review by SergioMorchon — APPROVED** [review]

**Pull request merged**
